name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      QT_VERSION: '6.2.4'
      QT_PATH: '${{ github.workspace }}/Qt/${{ env.QT_VERSION }}/msvc2019_64'
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - uses: jurplel/install-qt-action@v3
        with:
          version: ${{ env.QT_VERSION }}
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
      
      - name: Setup Dependencies
        run: |
          # Ghostscript
          Invoke-WebRequest -Uri "https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs1000/gs1000w64.exe" -OutFile "gs-installer.exe"
          Start-Process -FilePath "gs-installer.exe" -ArgumentList "/S /D=C:\ghostscript" -Wait
          mkdir -p deps/ghostscript/bin
          Copy-Item "C:\ghostscript\bin\*" -Destination "deps/ghostscript/bin" -Recurse
          
          # QPDF
          Invoke-WebRequest -Uri "https://github.com/qpdf/qpdf/releases/download/release-qpdf-10.6.3/qpdf-10.6.3-bin-mingw64.zip" -OutFile "qpdf.zip"
          Expand-Archive -Path "qpdf.zip" -DestinationPath "C:\qpdf"
          mkdir -p deps/qpdf/bin
          Copy-Item "C:\qpdf\qpdf-10.6.3\bin\*" -Destination "deps/qpdf/bin" -Recurse
      
      - name: Build and Package
        env:
          PATH: "${{ env.QT_PATH }}/bin;${{ env.PATH }}"
          Qt6_DIR: "${{ env.QT_PATH }}/bin"
        run: |
          python build.py --platform windows --type release --package --portable
      
      - uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            *.exe
            *.zip
          retention-days: 5
  
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - uses: jurplel/install-qt-action@v3
        with:
          version: '6.2.4'
          host: 'linux'
          target: 'desktop'
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake extra-cmake-modules ghostscript qpdf
      
      - name: Build and Package
        run: python3 build.py --platform linux --type release --package
      
      - uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: dist/
          retention-days: 5