name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.2.4'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          modules: 'qtwidgets qtconcurrent'
      
      - name: Download Ghostscript
        run: |
          Invoke-WebRequest -Uri "https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs1000/gs1000w64.exe" -OutFile "gs-installer.exe"
          Start-Process -FilePath "gs-installer.exe" -ArgumentList "/S /D=C:\ghostscript" -Wait
          mkdir -p deps/ghostscript/bin
          Copy-Item "C:\ghostscript\bin\*" -Destination "deps/ghostscript/bin" -Recurse
      
      - name: Download QPDF
        run: |
          Invoke-WebRequest -Uri "https://github.com/qpdf/qpdf/releases/download/release-qpdf-10.6.3/qpdf-10.6.3-bin-mingw64.zip" -OutFile "qpdf.zip"
          Expand-Archive -Path "qpdf.zip" -DestinationPath "C:\qpdf"
          mkdir -p deps/qpdf/bin
          Copy-Item "C:\qpdf\qpdf-10.6.3\bin\*" -Destination "deps/qpdf/bin" -Recurse
      
      - name: Build
        run: |
          python build.py --platform windows --type release
      
      - name: Create Package
        run: |
          python build.py --platform windows --type release --package --portable
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows-build
          path: |
            *.exe
            *.zip
  
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake extra-cmake-modules qtbase5-dev libqt5concurrent5 qt5-qmake qttools5-dev-tools ghostscript qpdf
      
      - name: Build
        run: |
          python3 build.py --platform linux --type release
      
      - name: Create Package
        run: |
          python3 build.py --platform linux --type release --package
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linux-build
          path: dist/
