name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.2.4'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          # The qtbase module (which includes Widgets and Concurrent) is installed by default
      
      - name: Download Ghostscript
        run: |
          Invoke-WebRequest -Uri "https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs1000/gs1000w64.exe" -OutFile "gs-installer.exe"
          Start-Process -FilePath "gs-installer.exe" -ArgumentList "/S /D=C:\ghostscript" -Wait
          mkdir -p deps/ghostscript/bin
          Copy-Item "C:\ghostscript\bin\*" -Destination "deps/ghostscript/bin" -Recurse
      
      - name: Download QPDF
        run: |
          Invoke-WebRequest -Uri "https://github.com/qpdf/qpdf/releases/download/release-qpdf-10.6.3/qpdf-10.6.3-bin-mingw64.zip" -OutFile "qpdf.zip"
          Expand-Archive -Path "qpdf.zip" -DestinationPath "C:\qpdf"
          mkdir -p deps/qpdf/bin
          Copy-Item "C:\qpdf\qpdf-10.6.3\bin\*" -Destination "deps/qpdf/bin" -Recurse
      
      # Icon generation has been moved to a pre-build step
      # The app.ico file is now committed to the repository
      
      - name: Build
        run: |
          # Add Qt bin directory to PATH to ensure windeployqt can be found
          $env:PATH = "$env:IQTA_TOOLS/Qt/6.2.4/msvc2019_64/bin;$env:PATH"
          # Set Qt6_DIR for the build script to find windeployqt
          $env:Qt6_DIR = "$env:IQTA_TOOLS/Qt/6.2.4/msvc2019_64/bin"
          python build.py --platform windows --type release
      
      - name: Create Package
        run: |
          # Add Qt bin directory to PATH to ensure windeployqt can be found
          $env:PATH = "$env:IQTA_TOOLS/Qt/6.2.4/msvc2019_64/bin;$env:PATH"
          # Set Qt6_DIR for the build script to find windeployqt
          $env:Qt6_DIR = "$env:IQTA_TOOLS/Qt/6.2.4/msvc2019_64/bin"
          python build.py --platform windows --type release --package --portable
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            *.exe
            *.zip
          retention-days: 5
  
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.2.4'
          host: 'linux'
          target: 'desktop'
          # The qtbase module (which includes Widgets and Concurrent) is installed by default
      
      - name: Install Additional Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake extra-cmake-modules ghostscript qpdf
      
      - name: Build
        run: |
          python3 build.py --platform linux --type release
      
      - name: Create Package
        run: |
          python3 build.py --platform linux --type release --package
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: dist/
          retention-days: 5